# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sander_cohere_com/script_bpe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sander_cohere_com/script_bpe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sander_cohere_com/script_bpe/CMakeFiles /home/sander_cohere_com/script_bpe//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sander_cohere_com/script_bpe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fast_tokenizer_cpp_std

# Build rule for target.
fast_tokenizer_cpp_std: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fast_tokenizer_cpp_std
.PHONY : fast_tokenizer_cpp_std

# fast build rule for target.
fast_tokenizer_cpp_std/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_std.dir/build.make CMakeFiles/fast_tokenizer_cpp_std.dir/build
.PHONY : fast_tokenizer_cpp_std/fast

#=============================================================================
# Target rules for targets named fast_tokenizer_cpp_absl

# Build rule for target.
fast_tokenizer_cpp_absl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fast_tokenizer_cpp_absl
.PHONY : fast_tokenizer_cpp_absl

# fast build rule for target.
fast_tokenizer_cpp_absl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_absl.dir/build.make CMakeFiles/fast_tokenizer_cpp_absl.dir/build
.PHONY : fast_tokenizer_cpp_absl/fast

#=============================================================================
# Target rules for targets named fast_tokenizer_cpp_gtl

# Build rule for target.
fast_tokenizer_cpp_gtl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fast_tokenizer_cpp_gtl
.PHONY : fast_tokenizer_cpp_gtl

# fast build rule for target.
fast_tokenizer_cpp_gtl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_gtl.dir/build.make CMakeFiles/fast_tokenizer_cpp_gtl.dir/build
.PHONY : fast_tokenizer_cpp_gtl/fast

#=============================================================================
# Target rules for targets named fast_tokenizer_cpp_robinhood

# Build rule for target.
fast_tokenizer_cpp_robinhood: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fast_tokenizer_cpp_robinhood
.PHONY : fast_tokenizer_cpp_robinhood

# fast build rule for target.
fast_tokenizer_cpp_robinhood/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_robinhood.dir/build.make CMakeFiles/fast_tokenizer_cpp_robinhood.dir/build
.PHONY : fast_tokenizer_cpp_robinhood/fast

#=============================================================================
# Target rules for targets named benchmark_cpp_fast_std

# Build rule for target.
benchmark_cpp_fast_std: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_cpp_fast_std
.PHONY : benchmark_cpp_fast_std

# fast build rule for target.
benchmark_cpp_fast_std/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_std.dir/build.make CMakeFiles/benchmark_cpp_fast_std.dir/build
.PHONY : benchmark_cpp_fast_std/fast

#=============================================================================
# Target rules for targets named benchmark_cpp_fast_absl

# Build rule for target.
benchmark_cpp_fast_absl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_cpp_fast_absl
.PHONY : benchmark_cpp_fast_absl

# fast build rule for target.
benchmark_cpp_fast_absl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_absl.dir/build.make CMakeFiles/benchmark_cpp_fast_absl.dir/build
.PHONY : benchmark_cpp_fast_absl/fast

#=============================================================================
# Target rules for targets named benchmark_cpp_fast_gtl

# Build rule for target.
benchmark_cpp_fast_gtl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_cpp_fast_gtl
.PHONY : benchmark_cpp_fast_gtl

# fast build rule for target.
benchmark_cpp_fast_gtl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_gtl.dir/build.make CMakeFiles/benchmark_cpp_fast_gtl.dir/build
.PHONY : benchmark_cpp_fast_gtl/fast

#=============================================================================
# Target rules for targets named benchmark_cpp_fast_robinhood

# Build rule for target.
benchmark_cpp_fast_robinhood: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_cpp_fast_robinhood
.PHONY : benchmark_cpp_fast_robinhood

# fast build rule for target.
benchmark_cpp_fast_robinhood/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_robinhood.dir/build.make CMakeFiles/benchmark_cpp_fast_robinhood.dir/build
.PHONY : benchmark_cpp_fast_robinhood/fast

script_bpe/bpe/fast/benchmark_cpp_fast.o: script_bpe/bpe/fast/benchmark_cpp_fast.cpp.o
.PHONY : script_bpe/bpe/fast/benchmark_cpp_fast.o

# target to build an object file
script_bpe/bpe/fast/benchmark_cpp_fast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_std.dir/build.make CMakeFiles/benchmark_cpp_fast_std.dir/script_bpe/bpe/fast/benchmark_cpp_fast.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_absl.dir/build.make CMakeFiles/benchmark_cpp_fast_absl.dir/script_bpe/bpe/fast/benchmark_cpp_fast.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_gtl.dir/build.make CMakeFiles/benchmark_cpp_fast_gtl.dir/script_bpe/bpe/fast/benchmark_cpp_fast.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_robinhood.dir/build.make CMakeFiles/benchmark_cpp_fast_robinhood.dir/script_bpe/bpe/fast/benchmark_cpp_fast.cpp.o
.PHONY : script_bpe/bpe/fast/benchmark_cpp_fast.cpp.o

script_bpe/bpe/fast/benchmark_cpp_fast.i: script_bpe/bpe/fast/benchmark_cpp_fast.cpp.i
.PHONY : script_bpe/bpe/fast/benchmark_cpp_fast.i

# target to preprocess a source file
script_bpe/bpe/fast/benchmark_cpp_fast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_std.dir/build.make CMakeFiles/benchmark_cpp_fast_std.dir/script_bpe/bpe/fast/benchmark_cpp_fast.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_absl.dir/build.make CMakeFiles/benchmark_cpp_fast_absl.dir/script_bpe/bpe/fast/benchmark_cpp_fast.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_gtl.dir/build.make CMakeFiles/benchmark_cpp_fast_gtl.dir/script_bpe/bpe/fast/benchmark_cpp_fast.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_robinhood.dir/build.make CMakeFiles/benchmark_cpp_fast_robinhood.dir/script_bpe/bpe/fast/benchmark_cpp_fast.cpp.i
.PHONY : script_bpe/bpe/fast/benchmark_cpp_fast.cpp.i

script_bpe/bpe/fast/benchmark_cpp_fast.s: script_bpe/bpe/fast/benchmark_cpp_fast.cpp.s
.PHONY : script_bpe/bpe/fast/benchmark_cpp_fast.s

# target to generate assembly for a file
script_bpe/bpe/fast/benchmark_cpp_fast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_std.dir/build.make CMakeFiles/benchmark_cpp_fast_std.dir/script_bpe/bpe/fast/benchmark_cpp_fast.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_absl.dir/build.make CMakeFiles/benchmark_cpp_fast_absl.dir/script_bpe/bpe/fast/benchmark_cpp_fast.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_gtl.dir/build.make CMakeFiles/benchmark_cpp_fast_gtl.dir/script_bpe/bpe/fast/benchmark_cpp_fast.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_robinhood.dir/build.make CMakeFiles/benchmark_cpp_fast_robinhood.dir/script_bpe/bpe/fast/benchmark_cpp_fast.cpp.s
.PHONY : script_bpe/bpe/fast/benchmark_cpp_fast.cpp.s

script_bpe/bpe/fast/bpe_core.o: script_bpe/bpe/fast/bpe_core.cpp.o
.PHONY : script_bpe/bpe/fast/bpe_core.o

# target to build an object file
script_bpe/bpe/fast/bpe_core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_std.dir/build.make CMakeFiles/fast_tokenizer_cpp_std.dir/script_bpe/bpe/fast/bpe_core.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_absl.dir/build.make CMakeFiles/fast_tokenizer_cpp_absl.dir/script_bpe/bpe/fast/bpe_core.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_gtl.dir/build.make CMakeFiles/fast_tokenizer_cpp_gtl.dir/script_bpe/bpe/fast/bpe_core.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_robinhood.dir/build.make CMakeFiles/fast_tokenizer_cpp_robinhood.dir/script_bpe/bpe/fast/bpe_core.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_std.dir/build.make CMakeFiles/benchmark_cpp_fast_std.dir/script_bpe/bpe/fast/bpe_core.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_absl.dir/build.make CMakeFiles/benchmark_cpp_fast_absl.dir/script_bpe/bpe/fast/bpe_core.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_gtl.dir/build.make CMakeFiles/benchmark_cpp_fast_gtl.dir/script_bpe/bpe/fast/bpe_core.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_robinhood.dir/build.make CMakeFiles/benchmark_cpp_fast_robinhood.dir/script_bpe/bpe/fast/bpe_core.cpp.o
.PHONY : script_bpe/bpe/fast/bpe_core.cpp.o

script_bpe/bpe/fast/bpe_core.i: script_bpe/bpe/fast/bpe_core.cpp.i
.PHONY : script_bpe/bpe/fast/bpe_core.i

# target to preprocess a source file
script_bpe/bpe/fast/bpe_core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_std.dir/build.make CMakeFiles/fast_tokenizer_cpp_std.dir/script_bpe/bpe/fast/bpe_core.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_absl.dir/build.make CMakeFiles/fast_tokenizer_cpp_absl.dir/script_bpe/bpe/fast/bpe_core.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_gtl.dir/build.make CMakeFiles/fast_tokenizer_cpp_gtl.dir/script_bpe/bpe/fast/bpe_core.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_robinhood.dir/build.make CMakeFiles/fast_tokenizer_cpp_robinhood.dir/script_bpe/bpe/fast/bpe_core.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_std.dir/build.make CMakeFiles/benchmark_cpp_fast_std.dir/script_bpe/bpe/fast/bpe_core.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_absl.dir/build.make CMakeFiles/benchmark_cpp_fast_absl.dir/script_bpe/bpe/fast/bpe_core.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_gtl.dir/build.make CMakeFiles/benchmark_cpp_fast_gtl.dir/script_bpe/bpe/fast/bpe_core.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_robinhood.dir/build.make CMakeFiles/benchmark_cpp_fast_robinhood.dir/script_bpe/bpe/fast/bpe_core.cpp.i
.PHONY : script_bpe/bpe/fast/bpe_core.cpp.i

script_bpe/bpe/fast/bpe_core.s: script_bpe/bpe/fast/bpe_core.cpp.s
.PHONY : script_bpe/bpe/fast/bpe_core.s

# target to generate assembly for a file
script_bpe/bpe/fast/bpe_core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_std.dir/build.make CMakeFiles/fast_tokenizer_cpp_std.dir/script_bpe/bpe/fast/bpe_core.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_absl.dir/build.make CMakeFiles/fast_tokenizer_cpp_absl.dir/script_bpe/bpe/fast/bpe_core.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_gtl.dir/build.make CMakeFiles/fast_tokenizer_cpp_gtl.dir/script_bpe/bpe/fast/bpe_core.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_robinhood.dir/build.make CMakeFiles/fast_tokenizer_cpp_robinhood.dir/script_bpe/bpe/fast/bpe_core.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_std.dir/build.make CMakeFiles/benchmark_cpp_fast_std.dir/script_bpe/bpe/fast/bpe_core.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_absl.dir/build.make CMakeFiles/benchmark_cpp_fast_absl.dir/script_bpe/bpe/fast/bpe_core.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_gtl.dir/build.make CMakeFiles/benchmark_cpp_fast_gtl.dir/script_bpe/bpe/fast/bpe_core.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_cpp_fast_robinhood.dir/build.make CMakeFiles/benchmark_cpp_fast_robinhood.dir/script_bpe/bpe/fast/bpe_core.cpp.s
.PHONY : script_bpe/bpe/fast/bpe_core.cpp.s

script_bpe/bpe/fast/python_bindings.o: script_bpe/bpe/fast/python_bindings.cpp.o
.PHONY : script_bpe/bpe/fast/python_bindings.o

# target to build an object file
script_bpe/bpe/fast/python_bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_std.dir/build.make CMakeFiles/fast_tokenizer_cpp_std.dir/script_bpe/bpe/fast/python_bindings.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_absl.dir/build.make CMakeFiles/fast_tokenizer_cpp_absl.dir/script_bpe/bpe/fast/python_bindings.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_gtl.dir/build.make CMakeFiles/fast_tokenizer_cpp_gtl.dir/script_bpe/bpe/fast/python_bindings.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_robinhood.dir/build.make CMakeFiles/fast_tokenizer_cpp_robinhood.dir/script_bpe/bpe/fast/python_bindings.cpp.o
.PHONY : script_bpe/bpe/fast/python_bindings.cpp.o

script_bpe/bpe/fast/python_bindings.i: script_bpe/bpe/fast/python_bindings.cpp.i
.PHONY : script_bpe/bpe/fast/python_bindings.i

# target to preprocess a source file
script_bpe/bpe/fast/python_bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_std.dir/build.make CMakeFiles/fast_tokenizer_cpp_std.dir/script_bpe/bpe/fast/python_bindings.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_absl.dir/build.make CMakeFiles/fast_tokenizer_cpp_absl.dir/script_bpe/bpe/fast/python_bindings.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_gtl.dir/build.make CMakeFiles/fast_tokenizer_cpp_gtl.dir/script_bpe/bpe/fast/python_bindings.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_robinhood.dir/build.make CMakeFiles/fast_tokenizer_cpp_robinhood.dir/script_bpe/bpe/fast/python_bindings.cpp.i
.PHONY : script_bpe/bpe/fast/python_bindings.cpp.i

script_bpe/bpe/fast/python_bindings.s: script_bpe/bpe/fast/python_bindings.cpp.s
.PHONY : script_bpe/bpe/fast/python_bindings.s

# target to generate assembly for a file
script_bpe/bpe/fast/python_bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_std.dir/build.make CMakeFiles/fast_tokenizer_cpp_std.dir/script_bpe/bpe/fast/python_bindings.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_absl.dir/build.make CMakeFiles/fast_tokenizer_cpp_absl.dir/script_bpe/bpe/fast/python_bindings.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_gtl.dir/build.make CMakeFiles/fast_tokenizer_cpp_gtl.dir/script_bpe/bpe/fast/python_bindings.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fast_tokenizer_cpp_robinhood.dir/build.make CMakeFiles/fast_tokenizer_cpp_robinhood.dir/script_bpe/bpe/fast/python_bindings.cpp.s
.PHONY : script_bpe/bpe/fast/python_bindings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... benchmark_cpp_fast_absl"
	@echo "... benchmark_cpp_fast_gtl"
	@echo "... benchmark_cpp_fast_robinhood"
	@echo "... benchmark_cpp_fast_std"
	@echo "... fast_tokenizer_cpp_absl"
	@echo "... fast_tokenizer_cpp_gtl"
	@echo "... fast_tokenizer_cpp_robinhood"
	@echo "... fast_tokenizer_cpp_std"
	@echo "... script_bpe/bpe/fast/benchmark_cpp_fast.o"
	@echo "... script_bpe/bpe/fast/benchmark_cpp_fast.i"
	@echo "... script_bpe/bpe/fast/benchmark_cpp_fast.s"
	@echo "... script_bpe/bpe/fast/bpe_core.o"
	@echo "... script_bpe/bpe/fast/bpe_core.i"
	@echo "... script_bpe/bpe/fast/bpe_core.s"
	@echo "... script_bpe/bpe/fast/python_bindings.o"
	@echo "... script_bpe/bpe/fast/python_bindings.i"
	@echo "... script_bpe/bpe/fast/python_bindings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

